### ISSUE TITLE
getMetadata: allow arbitrary request parameters

### ISSUE THREAD

**Issue by c0b** [GoogleCloudPlatform/google-cloud-node#2684]
the REST API reference mentioned `selectedFields` [2], and all google cloud services support the `fields` parameter [3]; but from [1] I'm not seeing how can I pass these parameters?

1. https://googlecloudplatform.github.io/google-cloud-node/#/docs/bigquery/0.9.6/bigquery/table?method=getMetadata
1. https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/get
2. https://developers.google.com/apis-explorer/#p/bigquery/v2/bigquery.tables.get

Background is we have some tens of thousands tables in bigquery want to figure out which ones are the most expensive ones (using the most storage), so write a little script to enumerate all table metadata, but it runs slow because each API call need to retrieve all metadata, want to use the `fields` to get only the needed information; if anyone knows a workaround, let me know.
(the *http* command here is an advanced version of curl; from https://httpie.org/)

```console
$ access_token=$(gcloud auth application-default print-access-token)
$ http https://www.googleapis.com/bigquery/v2/projects/<projectId>/datasets/<datasetId>/tables/<tableId> \
 fields==id,numBytes,numLongTermBytes,numRows,creationTime,expirationTime,lastModifiedTime,type,location \
 access_token==$access_token
[...]
{
 "id": "<projectId>:<datasetId>.<tableId>",
 "numBytes": "112728076",
 "numLongTermBytes": "0",
 "numRows": "28431",
 "creationTime": "1505962477264",
 "expirationTime": "1513738477264",
 "lastModifiedTime": "1505962477264",
 "type": "TABLE",
 "location": "US"
}
```

**Comment by c0b** [comment]
I see the `fields` parameter is the use case to mitigate the problem resolved by GraphQL API, but is it possible to ask google services to have GraphQL API?

**Comment by callmehiphop** [comment]
@stephenplusplus I don't think it is very common for get/getMetadata to accept query parameters, however do you think we should add support for this in the common library?

**Comment by stephenplusplus** [comment]
I do! Best to be as raw as possible in the common layer.

**Comment by tejohnso** [comment]
@c0b have you tried eg `getMetadata({fields: "lastModifiedTime"})`?
It works in the storage module.

**Comment by c0b** [comment]
no; I did try that do not work in `@google-cloud/bigquery@0.9.6`; current getMetadata take one parameter only which is expected to be the callback function, if pass in an obj then the error is `TypeError: callback is not a function`

**Comment by c0b** [comment]
@tejohnso the storage module works because of #2626 storage has its own repo that has support of that

https://github.com/googleapis/nodejs-storage/search?q=getMetadata+path:src

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-bigquery#11
