### ISSUE TITLE
Initializing Bigtable fails on keyFilename in v0.6.0

### ISSUE THREAD

**Issue by sararob** [GoogleCloudPlatform/google-cloud-node#1842]
When I initialize Bigtable in version 0.6.0 I get this error:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'keyfile.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Auth.getAuthClient (/Users/sararob/Dev/cloud/bigtable/emojis/node_modules/@google-cloud/bigtable/node_modules/@google-cloud/common/node_modules/google-auto-auth/index.js:50:47)
    at Bigtable.GrpcService.getGrpcCredentials_ (/Users/sararob/Dev/cloud/bigtable/emojis/node_modules/@google-cloud/bigtable/node_modules/@google-cloud/common/src/grpc-service.js:727:19)
    at Bigtable.GrpcService.request (/Users/sararob/Dev/cloud/bigtable/emojis/node_modules/@google-cloud/bigtable/node_modules/@google-cloud/common/src/grpc-service.js:231:10)
    at Instance.GrpcServiceObject.request (/Users/sararob/Dev/cloud/bigtable/emojis/node_modules/@google-cloud/bigtable/node_modules/@google-cloud/common/src/grpc-service-object.js:113:30)
    at Instance.wrapper (/Users/sararob/Dev/cloud/bigtable/emojis/node_modules/@google-cloud/bigtable/node_modules/@google-cloud/common/src/util.js:660:29)
    at Instance.createTable (/Users/sararob/Dev/cloud/bigtable/emojis/node_modules/@google-cloud/bigtable/src/instance.js:482:8)
```
It works fine in version 0.5.1 (I haven't tried any in between). 

#### Environment details

  - OS: Mac OSX El Capitan 10.11.6
  - Node.js version: 4.2.3
  - npm version: 2.14.7
  - google-cloud-node/bigtable version: 0.6.0

#### Steps to reproduce

  1. require `@google-cloud/bigtable` version `0.6.0`
  2. initialize Bigtable with the following:

```
var bigtable = require('@google-cloud/bigtable')({
  projectId: 'your-project-id',
  keyFilename: '/path/to/keyfile.json'
});

```

**Comment by stephenplusplus** [comment]
Woops, I'll make a patch in google-auto-auth (https://github.com/stephenplusplus/google-auto-auth/blob/43d0e1d5386cfcf742a3cc2f15903a3f187267c0/index.js#L50). For now, if you provide an absolute path, it should continue working.

```diff
-  keyFilename: 'keyfile.json'
+  keyFilename: require.resolve('keyfile.json')
```

**Comment by sararob** [comment]
Thanks!

**Comment by stephenplusplus** [comment]
Fix has been made in google-auto-auth ([fix](https://github.com/stephenplusplus/google-auto-auth/commit/58fcee33ca558e200bc52ab71d23e51f1048afa0)) and it was released as google-auto-auth@0.5.2. The `@google-cloud/{service}` modules will install the update immediately. The `google-cloud` package will get the update in our next release.

Thanks for reporting!

**Comment by jgeewax** [comment]
Just ran into this also -- when's the next google-cloud update coming ? Should be a minor release with the new deps, right?

**Comment by stephenplusplus** [comment]
Good call, I updated my example. I'll try to get a release out today, but it will be a minor, as we've had some breaking changes since our last release.
